# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 87ac9968350cb02d1ae267c0e24d2c0451e17f4560d49cca908c8f8b77374a3ea8592c2bda6f76de41117a16ce0cdb781811c3a46abe2e164a5b47f721b63d5a

test:
  secret_key_base: e25ef546fb5cd78663ff8261831c3d88af8956e316c362f405fe72a3b1f96fab008f0800e1dafaa34d8a30e0658ce622b67b6b31b77007a76b01c15ab801c03d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
